spring:
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  seed:
    enabled: false
